name: app-rust

on:
  push:
    paths:
      - app_rust/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ["lint", "test"]
    steps:
      - uses: actions/checkout@v4

      - name: Rust Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Dependencies
        working-directory: ./app_rust
        run: |
          rustup update stable
          cargo install --locked cargo-nextest

      - name: Linting
        if: matrix.step == 'lint'
        working-directory: ./app_rust
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Testing
        if: matrix.step == 'test'
        working-directory: ./app_rust
        run: cargo nextest run

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        working-directory: ./app_rust
        run: |
          docker build --build-arg CACHEBUST=$(date +%s) -t app_rust .

      - name: Push Docker Image
        working-directory: ./app_rust
        run: |
          docker tag app_rust:latest ${{ secrets.DOCKER_USERNAME }}/app_rust:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/app_rust:latest

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Install Dependencies
        working-directory: ./app_rust
        run: |
          rustup update stable
          cargo install --locked cargo-audit

      - name: Run cargo-audit for Vulnerability Checks
        working-directory: ./app_rust
        run: cargo audit
